version: '3.9'
services:
  api_stripe:
    build: { context: ./backend/stripe, target: prod }
    container_name: api_stripe
    env_file: ./backend/stripe/.env
    restart: unless-stopped

  proxy:
    build: { context: ./nginx }
    container_name: proxy
    ports: [ '80:80', '443:443' ]
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
      - ./nginx/letsencrypt:/etc/letsencrypt:ro
    depends_on: [api_stripe]
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on: [proxy]
    entrypoint: sh
    command: -c "if [ -n '-d api.stripe.salchimonster.com' ]; then certbot certonly -n --keep-until-expiring --webroot -w /var/www/certbot -d api.stripe.salchimonster.com --email \"andrew19f@gmail.com\" --agree-tos --no-eff-email ; fi; trap exit TERM; while :; do certbot renew -n --webroot -w /var/www/certbot --quiet || true; sleep 12h; done"
    restart: unless-stopped

